package:
  name: m2w64-gcc
  version: 20250618

source:
  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-clang-aarch64-windows-default-manifest-6.4-4-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20250618-clangarm64/mingw-w64-clang-aarch64-windows-default-manifest-6.4-4-any.pkg.tar.zst
    sha256: 3bde403468a3388aa7b8b0004955d37271e57d19c3a86467832393731958e18e
    folder: binary-mingw-w64-clang-aarch64-windows-default-manifest

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-windows-default-manifest-6.4-4.src.tar.gz
      - https://github.com/conda-forge/msys2-recipes/releases/download/20250618-clangarm64/mingw-w64-windows-default-manifest-6.4-4.src.tar.gz
    sha256: c608729d05c85968580a5cd8442d06aad5d649b8375b3ccc2943f337b77ee322
    folder: source-mingw-w64-clang-aarch64-windows-default-manifest

  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-clang-aarch64-headers-git-13.0.0.r1.gb45abfec4-1-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20250618-clangarm64/mingw-w64-clang-aarch64-headers-git-13.0.0.r1.gb45abfec4-1-any.pkg.tar.zst
    sha256: ecc3c6fe5ea32bfcaa7d127c42715be8bc785bee56ce3032a65ad1fc997af67e
    folder: binary-mingw-w64-clang-aarch64-headers-git

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-headers-git-13.0.0.r1.gb45abfec4-1.src.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20250618-clangarm64/mingw-w64-headers-git-13.0.0.r1.gb45abfec4-1.src.tar.zst
    sha256: a5bf5d0cfd98628d8c8220d99e814f644fc2ac2fe2098f3f53d7c13eb957c7cf
    folder: source-mingw-w64-clang-aarch64-headers-git

  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-clang-aarch64-winpthreads-git-12.0.0.r81.g90abf784a-1-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20250618-clangarm64/mingw-w64-clang-aarch64-winpthreads-git-12.0.0.r81.g90abf784a-1-any.pkg.tar.zst
    sha256: 1f06eb2b280f5288436cd9f1d446f0416a65d1d009e61cb685627f06590e59fb
    folder: binary-mingw-w64-clang-aarch64-winpthreads-git

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-winpthreads-git-12.0.0.r81.g90abf784a-1.src.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20250618-clangarm64/mingw-w64-winpthreads-git-12.0.0.r81.g90abf784a-1.src.tar.zst
    sha256: bdc6f6116f8c70584e11eb2162515568b1241eb4e2c55b6f9f3b1c316e935c2d
    folder: source-mingw-w64-clang-aarch64-winpthreads-git

  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-clang-aarch64-libwinpthread-git-12.0.0.r81.g90abf784a-1-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20250618-clangarm64/mingw-w64-clang-aarch64-libwinpthread-git-12.0.0.r81.g90abf784a-1-any.pkg.tar.zst
    sha256: 7f2f9b450026fa576d333aa5b6c5093e827477dfe4a402a7264b6b943a889581
    folder: binary-mingw-w64-clang-aarch64-libwinpthread-git

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-winpthreads-git-12.0.0.r81.g90abf784a-1.src.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20250618-clangarm64/mingw-w64-winpthreads-git-12.0.0.r81.g90abf784a-1.src.tar.zst
    sha256: bdc6f6116f8c70584e11eb2162515568b1241eb4e2c55b6f9f3b1c316e935c2d
    folder: source-mingw-w64-clang-aarch64-libwinpthread-git

  - url:
      - https://repo.msys2.org/mingw/ucrt64/mingw-w64-clang-aarch64-crt-git-13.0.0.r1.gb45abfec4-2-any.pkg.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20250618-clangarm64/mingw-w64-clang-aarch64-crt-git-13.0.0.r1.gb45abfec4-2-any.pkg.tar.zst
    sha256: 30dbcd14813d3a7099b950d68db2a32a69958cf3dcbdad620852aaee895e9d62
    folder: binary-mingw-w64-clang-aarch64-crt-git

  - url:
      - https://repo.msys2.org/mingw/sources/mingw-w64-crt-git-13.0.0.r1.gb45abfec4-2.src.tar.zst
      - https://github.com/conda-forge/msys2-recipes/releases/download/20250618-clangarm64/mingw-w64-crt-git-13.0.0.r1.gb45abfec4-2.src.tar.zst
    sha256: 6f58fc8aad4a0a621d51fbb0591272273767e6321803c874a26c826d3083f60b
    folder: source-mingw-w64-clang-aarch64-crt-git

build:
  number: 5
  error_overlinking: false

outputs:
  - name: mingw-w64-clang-aarch64-windows-default-manifest
    version: 6.4.4
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:

      run:
        - __unix   # [unix]
        - __win    # [win]

    about:
      home: https://cygwin.com/
      license: BSD
      summary: |
        Default Windows application manifest (mingw-w64)

  - name: mingw-w64-clang-aarch64-headers-git
    version: 13.0.0.r1.gb45abfec4.1
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:

      run:
        - __unix   # [unix]
        - __win    # [win]

    about:
      home: https://www.mingw-w64.org/
      license: ZPL-2.1 AND LGPL-2.1-or-later
      summary: |
        MinGW-w64 headers for Windows (mingw-w64)

  - name: mingw-w64-clang-aarch64-winpthreads-git
    version: 12.0.0.r81.g90abf784a.1
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:
        - mingw-w64-clang-aarch64-crt-git
        - mingw-w64-clang-aarch64-libwinpthread-git =12.0.0.r81.g90abf784a
      run:
        - __unix   # [unix]
        - __win    # [win]
        - mingw-w64-clang-aarch64-crt-git
        - mingw-w64-clang-aarch64-libwinpthread-git =12.0.0.r81.g90abf784a
    about:
      home: https://www.mingw-w64.org/
      license: MIT AND BSD-3-Clause-Clear
      summary: |
        MinGW-w64 winpthreads library (mingw-w64)

  - name: mingw-w64-clang-aarch64-libwinpthread-git
    version: 12.0.0.r81.g90abf784a.1
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:

      run:
        - __unix   # [unix]
        - __win    # [win]

    about:
      home: https://www.mingw-w64.org/
      license: MIT AND BSD-3-Clause-Clear
      summary: |
        MinGW-w64 winpthreads library (mingw-w64)

  - name: mingw-w64-clang-aarch64-crt-git
    version: 13.0.0.r1.gb45abfec4.2
    script: install_pkg.bat  # [build_platform.startswith("win-")]
    script: install_pkg.sh   # [not build_platform.startswith("win-")]
    build:
      noarch: generic
    requirements:
      host:
        - mingw-w64-clang-aarch64-headers-git
      run:
        - __unix   # [unix]
        - __win    # [win]
        - mingw-w64-clang-aarch64-headers-git
    about:
      home: https://www.mingw-w64.org/
      license: ZPL-2.1
      summary: |
        MinGW-w64 CRT for Windows (mingw-w64)

  - name: m2w64-sysroot_win-arm64
    version: 13.0.0.r1.gb45abfec4.2
    build:
      noarch: generic
    requirements:
      run:
        - __unix   # [unix]
        - __win    # [win]
        - mingw-w64-clang-aarch64-windows-default-manifest
        - mingw-w64-clang-aarch64-crt-git
        - mingw-w64-clang-aarch64-headers-git
        - mingw-w64-clang-aarch64-winpthreads-git
    about:
      home: https://mingw-w64.sourceforge.io/
      summary: |
        MinGW-w64 sysroot for Windows
      license: ZPL-2.1 AND LGPL-2.1-or-later and MIT AND BSD-3-Clause-Clear

about:
  home: https://github.com/conda-forge/m2w64-gcc-feedstock
  summary: Repackaged mingw-w64 binaries
  license: ZPL-2.1 AND LGPL-2.1-or-later and MIT AND BSD-3-Clause-Clear

extra:
  recipe-maintainers:
    - isuruf
